-- Etape 1
ALTER TABLE BIB_MEMBRES ADD CONSTRAINT UN_MEMBRES UNIQUE (NOM, PRENOM, TELEPHONE);

-- Etape 2
ALTER TABLE BIB_EXEMPLAIRES MODIFY ETAT CHAR(2);

-- Etape 3
-- Il n'est pas possible de modifier la clause ON DELETE
--  => il faut détruire et recréer la contrainte
ALTER TABLE BIB_DETAILSEMPRUNTS DROP CONSTRAINT FK_DETAILS_EMPRUNTS;

ALTER TABLE BIB_DETAILSEMPRUNTS ADD CONSTRAINT FK_DETAILS_EMPRUNTS FOREIGN KEY (EMPRUNT) REFERENCES BIB_EMPRUNTS(NUMERO) ON DELETE CASCADE;

-- Etape 4
ALTER TABLE BIB_EXEMPLAIRES MODIFY ETAT DEFAULT 'NE';

-- Etape 5
RENAME BIB_DETAILSEMPRUNTS TO BIB_DETAILS;

-- Etape 6
CREATE INDEX IX_OUVRAGES_GENRES ON BIB_OUVRAGES(GENRE);

CREATE INDEX IX_EXEMPLAIRES_ISBN ON BIB_EXEMPLAIRES(ISBN);

CREATE INDEX IX_EMPRUNTS_MEMBRE ON BIB_EMPRUNTS(MEMBRE);

CREATE INDEX IX_DETAILS_EMPRUNT ON BIB_DETAILS(EMPRUNT);

CREATE INDEX IX_DETIALS_EXEMPLAIRES ON BIB_DETAILS(ISBN, EXEMPLAIRE);
